name: Unit Tests

env:
  ENVIRONMENT: test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    name: Run unit tests
    steps:
      - uses: actions/checkout@v3
      - name: "Create .env file"
        run: |
          touch .env
          echo ENVIRONMENT=${{ env.ENVIRONMENT }} >> .env
          echo HOSTNAME=${{ secrets.HOSTNAME}} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run test scripts
        run: yarn test
        # Github token to run public workflows
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
